/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 src/assets/models/book/Book.glb -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import book3DModelFile from "../../../assets/models/book/Book.glb";
import { useTurnTable } from "../../../hooks/use-turn-table";
type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Cube_3: THREE.Mesh;
    Cube_4: THREE.Mesh;
    Cube_5: THREE.Mesh;
    Cube_6: THREE.Mesh;
    Cube_7: THREE.Mesh;
    Cube_8: THREE.Mesh;
  };
  materials: {
    Paper: THREE.MeshBasicMaterial;
    Ink: THREE.MeshBasicMaterial;
    Book: THREE.MeshBasicMaterial;
    Paper_shade: THREE.MeshBasicMaterial;
    Paper_shade_2: THREE.MeshBasicMaterial;
    Book_shade: THREE.MeshBasicMaterial;
    Book_Title: THREE.MeshBasicMaterial;
    Book_Code: THREE.MeshBasicMaterial;
  };
};

export function Book3dModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(book3DModelFile) as GLTFResult;
  const { group } = useTurnTable();

  return (
    <group {...props} dispose={null} ref={group} scale={0.6}>
      <group rotation={[1.05, 0, 0]} scale={[0.73, 0.05, 0.61]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Paper} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Ink} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.Book} />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials.Paper_shade}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials.Paper_shade_2}
        />
        <mesh
          geometry={nodes.Cube_6.geometry}
          material={materials.Book_shade}
        />
        <mesh
          geometry={nodes.Cube_7.geometry}
          material={materials.Book_Title}
        />
        <mesh geometry={nodes.Cube_8.geometry} material={materials.Book_Code} />
      </group>
    </group>
  );
}

useGLTF.preload(book3DModelFile);
