/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 src/assets/models/Burnt_Car/BurntCar1.gltf -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import burntCarModel1File from "../../../assets/models/Burnt_Car/BurntCar1.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
  };
  materials: {
    Burnt_Base: THREE.MeshBasicMaterial;
    Dark_Shade: THREE.MeshBasicMaterial;
    Burnt_High: THREE.MeshBasicMaterial;
    Burnt_Mid: THREE.MeshBasicMaterial;
  };
};

export function BurntCarModel1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(burntCarModel1File) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.35, 0.09]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Burnt_Base} />
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials.Dark_Shade}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials.Burnt_High}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials.Burnt_Mid}
        />
      </group>
    </group>
  );
}

useGLTF.preload(burntCarModel1File);
