/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 src/assets/models/Burnt_Car/BurntCar3.gltf -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import burntCarModel3File from "../../../assets/models/Burnt_Car/BurntCar3.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane002_2: THREE.Mesh;
    Plane002_3: THREE.Mesh;
  };
  materials: {
    Dark_Shade: THREE.MeshBasicMaterial;
    Burnt_Mid: THREE.MeshBasicMaterial;
    Burnt_High: THREE.MeshBasicMaterial;
    Burnt_Base: THREE.MeshBasicMaterial;
  };
};

export function BurntCarModel3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(burntCarModel3File) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.31, 0.04]}>
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials.Dark_Shade}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials.Burnt_Mid}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials.Burnt_High}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials.Burnt_Base}
        />
      </group>
    </group>
  );
}

useGLTF.preload(burntCarModel3File);
