/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 assets/models/Barrier/Barrier.glb -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CHUNK_2_MESH: THREE.Mesh
    CHUNK_2_MESH_1: THREE.Mesh
    CHUNK_2_MESH_2: THREE.Mesh
    CHUNK_1_MESH: THREE.Mesh
    CHUNK_1_MESH_1: THREE.Mesh
    CHUNK_1_MESH_2: THREE.Mesh
    CHUNK_1_MESH_3: THREE.Mesh
    CHUNK_3_MESH: THREE.Mesh
    CHUNK_3_MESH_1: THREE.Mesh
    CHUNK_3_MESH_2: THREE.Mesh
    CHUNK_4_MESH: THREE.Mesh
    CHUNK_4_MESH_1: THREE.Mesh
    CHUNK_4_MESH_2: THREE.Mesh
    CHUNK_4_MESH_3: THREE.Mesh
  }
  materials: {
    Road_Props_Yellow_Signal: THREE.MeshBasicMaterial
    High_Concrete: THREE.MeshBasicMaterial
    Concrete: THREE.MeshBasicMaterial
    ['Road_Props_Yellow_Signal.002']: THREE.MeshBasicMaterial
    ['Road_Props_Yellow_Signal_Shade.002']: THREE.MeshBasicMaterial
    ['High_Concrete.002']: THREE.MeshBasicMaterial
    ['Concrete.002']: THREE.MeshBasicMaterial
    ['Road_Props_Yellow_Signal.003']: THREE.MeshBasicMaterial
    ['High_Concrete.003']: THREE.MeshBasicMaterial
    ['Concrete.003']: THREE.MeshBasicMaterial
    ['Road_Props_Yellow_Signal.004']: THREE.MeshBasicMaterial
    ['Road_Props_Yellow_Signal_Shade.004']: THREE.MeshBasicMaterial
    ['High_Concrete.004']: THREE.MeshBasicMaterial
    ['Concrete.004']: THREE.MeshBasicMaterial
  }
}

type ActionName = 'CHUNK_2A_BREAK' | 'CHUNK_1_BREAK' | 'CHUNK_3A_BREAK' | 'CHUNK_4_BREAK'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/../assets/models/Barrier/Barrier.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CHUNK_2" scale={[1, 0.59, 1]}>
          <mesh name="CHUNK_2_MESH" geometry={nodes.CHUNK_2_MESH.geometry} material={materials.Road_Props_Yellow_Signal} />
          <mesh name="CHUNK_2_MESH_1" geometry={nodes.CHUNK_2_MESH_1.geometry} material={materials.High_Concrete} />
          <mesh name="CHUNK_2_MESH_2" geometry={nodes.CHUNK_2_MESH_2.geometry} material={materials.Concrete} />
        </group>
        <group name="CHUNK_1" scale={[1, 0.59, 1]}>
          <mesh name="CHUNK_1_MESH" geometry={nodes.CHUNK_1_MESH.geometry} material={materials['Road_Props_Yellow_Signal.002']} />
          <mesh name="CHUNK_1_MESH_1" geometry={nodes.CHUNK_1_MESH_1.geometry} material={materials['Road_Props_Yellow_Signal_Shade.002']} />
          <mesh name="CHUNK_1_MESH_2" geometry={nodes.CHUNK_1_MESH_2.geometry} material={materials['High_Concrete.002']} />
          <mesh name="CHUNK_1_MESH_3" geometry={nodes.CHUNK_1_MESH_3.geometry} material={materials['Concrete.002']} />
        </group>
        <group name="CHUNK_3" scale={[1, 0.59, 1]}>
          <mesh name="CHUNK_3_MESH" geometry={nodes.CHUNK_3_MESH.geometry} material={materials['Road_Props_Yellow_Signal.003']} />
          <mesh name="CHUNK_3_MESH_1" geometry={nodes.CHUNK_3_MESH_1.geometry} material={materials['High_Concrete.003']} />
          <mesh name="CHUNK_3_MESH_2" geometry={nodes.CHUNK_3_MESH_2.geometry} material={materials['Concrete.003']} />
        </group>
        <group name="CHUNK_4" scale={[1, 0.59, 1]}>
          <mesh name="CHUNK_4_MESH" geometry={nodes.CHUNK_4_MESH.geometry} material={materials['Road_Props_Yellow_Signal.004']} />
          <mesh name="CHUNK_4_MESH_1" geometry={nodes.CHUNK_4_MESH_1.geometry} material={materials['Road_Props_Yellow_Signal_Shade.004']} />
          <mesh name="CHUNK_4_MESH_2" geometry={nodes.CHUNK_4_MESH_2.geometry} material={materials['High_Concrete.004']} />
          <mesh name="CHUNK_4_MESH_3" geometry={nodes.CHUNK_4_MESH_3.geometry} material={materials['Concrete.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../assets/models/Barrier/Barrier.glb')
