/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 assets/models/Male_Character.glb -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HANDED_MAUL_MESH: THREE.Mesh
    HANDED_MAUL_MESH_1: THREE.Mesh
    HANDED_MAUL_MESH_2: THREE.Mesh
    RIFLE: THREE.Mesh
    BULLET_TRAIL_MESH: THREE.Mesh
    BULLET_TRAIL_MESH_1: THREE.Mesh
    PACKED_MAUL_MESH: THREE.Mesh
    PACKED_MAUL_MESH_1: THREE.Mesh
    PACKED_MAUL_MESH_2: THREE.Mesh
    PACKED_MAUL_MESH_3: THREE.Mesh
    MALE_BASE_MESH_1: THREE.SkinnedMesh
    MALE_BASE_MESH_2: THREE.SkinnedMesh
    MALE_BASE_MESH_3: THREE.SkinnedMesh
    MALE_BASE_MESH_4: THREE.SkinnedMesh
    MALE_BASE_MESH_5: THREE.SkinnedMesh
    MALE_BASE_MESH_6: THREE.SkinnedMesh
    MALE_BASE_MESH_7: THREE.SkinnedMesh
    MALE_BASE_MESH_8: THREE.SkinnedMesh
    MALE_BASE_MESH_9: THREE.SkinnedMesh
    MALE_BASE_MESH_10: THREE.SkinnedMesh
    MALE_BASE_MESH_11: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Wood: THREE.MeshBasicMaterial
    Metal: THREE.MeshBasicMaterial
    Metal_Shade: THREE.MeshBasicMaterial
    Hair: THREE.MeshBasicMaterial
    Smoke: THREE.MeshBasicMaterial
    Fire: THREE.MeshBasicMaterial
    Jacket_Shade: THREE.MeshBasicMaterial
    Skin_Base: THREE.MeshBasicMaterial
    Skin_Shade_2: THREE.MeshBasicMaterial
    Skin_Shade3: THREE.MeshBasicMaterial
    Skin_Shade_4: THREE.MeshBasicMaterial
    Jacket: THREE.MeshBasicMaterial
    Jacket_Inside: THREE.MeshBasicMaterial
    Jacket_Shade: THREE.MeshBasicMaterial
    Jacket_Shade2: THREE.MeshBasicMaterial
    Pants: THREE.MeshBasicMaterial
    Pants_Shade: THREE.MeshBasicMaterial
    Shoes: THREE.MeshBasicMaterial
  }
}

type ActionName = 'DEATH' | 'IDLE' | 'MAUL' | 'ROLL' | 'RUN' | 'SHOOTING'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/../assets/models/Male_Character.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="MALE_BASE_MESH">
            <skinnedMesh name="MALE_BASE_MESH_1" geometry={nodes.MALE_BASE_MESH_1.geometry} material={materials.Skin_Base} skeleton={nodes.MALE_BASE_MESH_1.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_2" geometry={nodes.MALE_BASE_MESH_2.geometry} material={materials.Skin_Shade_2} skeleton={nodes.MALE_BASE_MESH_2.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_3" geometry={nodes.MALE_BASE_MESH_3.geometry} material={materials.Skin_Shade3} skeleton={nodes.MALE_BASE_MESH_3.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_4" geometry={nodes.MALE_BASE_MESH_4.geometry} material={materials.Skin_Shade_4} skeleton={nodes.MALE_BASE_MESH_4.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_5" geometry={nodes.MALE_BASE_MESH_5.geometry} material={materials.Jacket} skeleton={nodes.MALE_BASE_MESH_5.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_6" geometry={nodes.MALE_BASE_MESH_6.geometry} material={materials.Jacket_Inside} skeleton={nodes.MALE_BASE_MESH_6.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_7" geometry={nodes.MALE_BASE_MESH_7.geometry} material={materials.Jacket_Shade} skeleton={nodes.MALE_BASE_MESH_7.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_8" geometry={nodes.MALE_BASE_MESH_8.geometry} material={materials.Jacket_Shade2} skeleton={nodes.MALE_BASE_MESH_8.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_9" geometry={nodes.MALE_BASE_MESH_9.geometry} material={materials.Pants} skeleton={nodes.MALE_BASE_MESH_9.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_10" geometry={nodes.MALE_BASE_MESH_10.geometry} material={materials.Pants_Shade} skeleton={nodes.MALE_BASE_MESH_10.skeleton} />
            <skinnedMesh name="MALE_BASE_MESH_11" geometry={nodes.MALE_BASE_MESH_11.geometry} material={materials.Shoes} skeleton={nodes.MALE_BASE_MESH_11.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../assets/models/Male_Character.glb')
