/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 src/assets/models/Burnt_Car/BurntCar2.gltf -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import burntCarModel2File from "../../../assets/models/Burnt_Car/BurntCar2.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane001_3: THREE.Mesh;
  };
  materials: {
    Dark_Shade: THREE.MeshBasicMaterial;
    Burnt_Base: THREE.MeshBasicMaterial;
    Burnt_High: THREE.MeshBasicMaterial;
    Burnt_Mid: THREE.MeshBasicMaterial;
  };
};

export function BurntCarModel2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(burntCarModel2File) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.28, -0.01]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.Dark_Shade}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials.Burnt_Base}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials.Burnt_High}
        />
        <mesh
          geometry={nodes.Plane001_3.geometry}
          material={materials.Burnt_Mid}
        />
      </group>
    </group>
  );
}

useGLTF.preload(burntCarModel2File);
