/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 assets/models/Bank/Bank.glb -t -r public
*/

import * as THREE from "three";

import { GLTF } from "three-stdlib";
import bank3DModelFile from "../../../assets/models/Bank/Bank.glb";
import { useGLTF } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    ROAD_1: THREE.Mesh;
    ROAD_2: THREE.Mesh;
    ROAD_3: THREE.Mesh;
    ROAD_4: THREE.Mesh;
    ROAD_5: THREE.Mesh;
    ROAD_6: THREE.Mesh;
    ROAD_7: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    Cube001_3: THREE.Mesh;
    Cube001_4: THREE.Mesh;
    Cube001_5: THREE.Mesh;
    Cube001_6: THREE.Mesh;
    A_C: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    SIDE_WALK: THREE.Mesh;
    AUTO_SERVICE: THREE.Mesh;
    VAN_BODY_MESH: THREE.Mesh;
    VAN_BODY_MESH_1: THREE.Mesh;
    VAN_BODY_MESH_2: THREE.Mesh;
    VAN_BODY_MESH_3: THREE.Mesh;
    VAN_BODY_MESH_4: THREE.Mesh;
    VAN_BODY_MESH_5: THREE.Mesh;
    VAN_BODY_MESH_6: THREE.Mesh;
    VAN_BODY_MESH_7: THREE.Mesh;
    BACK_WHEELS_MESH001: THREE.Mesh;
    BACK_WHEELS_MESH001_1: THREE.Mesh;
    BACK_WHEELS_MESH001_2: THREE.Mesh;
    FRONT_WHEELS_MESH001: THREE.Mesh;
    FRONT_WHEELS_MESH001_1: THREE.Mesh;
    FRONT_WHEELS_MESH001_2: THREE.Mesh;
    MIRRORS_MESH: THREE.Mesh;
    MIRRORS_MESH_1: THREE.Mesh;
    MIRRORS_MESH_2: THREE.Mesh;
    MIRRORS_MESH_3: THREE.Mesh;
    MIRRORS_MESH_4: THREE.Mesh;
    MIRRORS_MESH_5: THREE.Mesh;
    MIRRORS_MESH_6: THREE.Mesh;
    VAN_BODY_MESH001: THREE.Mesh;
    VAN_BODY_MESH001_1: THREE.Mesh;
    VAN_BODY_MESH001_2: THREE.Mesh;
    VAN_BODY_MESH001_3: THREE.Mesh;
    VAN_BODY_MESH001_4: THREE.Mesh;
    VAN_BODY_MESH001_5: THREE.Mesh;
    VAN_BODY_MESH001_6: THREE.Mesh;
    VAN_BODY_MESH001_7: THREE.Mesh;
    BACK_WHEELS_MESH002: THREE.Mesh;
    BACK_WHEELS_MESH002_1: THREE.Mesh;
    BACK_WHEELS_MESH002_2: THREE.Mesh;
    FRONT_WHEELS_MESH002: THREE.Mesh;
    FRONT_WHEELS_MESH002_1: THREE.Mesh;
    FRONT_WHEELS_MESH002_2: THREE.Mesh;
    MIRRORS_MESH001: THREE.Mesh;
    MIRRORS_MESH001_1: THREE.Mesh;
    MIRRORS_MESH001_2: THREE.Mesh;
    MIRRORS_MESH001_3: THREE.Mesh;
    MIRRORS_MESH001_4: THREE.Mesh;
    MIRRORS_MESH001_5: THREE.Mesh;
    MIRRORS_MESH001_6: THREE.Mesh;
    VAN_BODY_MESH002: THREE.Mesh;
    VAN_BODY_MESH002_1: THREE.Mesh;
    VAN_BODY_MESH002_2: THREE.Mesh;
    VAN_BODY_MESH002_3: THREE.Mesh;
    VAN_BODY_MESH002_4: THREE.Mesh;
    VAN_BODY_MESH002_5: THREE.Mesh;
    VAN_BODY_MESH002_6: THREE.Mesh;
    VAN_BODY_MESH002_7: THREE.Mesh;
    BACK_WHEELS_MESH003: THREE.Mesh;
    BACK_WHEELS_MESH003_1: THREE.Mesh;
    BACK_WHEELS_MESH003_2: THREE.Mesh;
    FRONT_WHEELS_MESH003: THREE.Mesh;
    FRONT_WHEELS_MESH003_1: THREE.Mesh;
    FRONT_WHEELS_MESH003_2: THREE.Mesh;
    MIRRORS_MESH002: THREE.Mesh;
    MIRRORS_MESH002_1: THREE.Mesh;
    MIRRORS_MESH002_2: THREE.Mesh;
    MIRRORS_MESH002_3: THREE.Mesh;
    MIRRORS_MESH002_4: THREE.Mesh;
    MIRRORS_MESH002_5: THREE.Mesh;
    MIRRORS_MESH002_6: THREE.Mesh;
    VAN_BODY_MESH003: THREE.Mesh;
    VAN_BODY_MESH003_1: THREE.Mesh;
    VAN_BODY_MESH003_2: THREE.Mesh;
    VAN_BODY_MESH003_3: THREE.Mesh;
    VAN_BODY_MESH003_4: THREE.Mesh;
    VAN_BODY_MESH003_5: THREE.Mesh;
    VAN_BODY_MESH003_6: THREE.Mesh;
    VAN_BODY_MESH003_7: THREE.Mesh;
    BACK_WHEELS_MESH004: THREE.Mesh;
    BACK_WHEELS_MESH004_1: THREE.Mesh;
    BACK_WHEELS_MESH004_2: THREE.Mesh;
    FRONT_WHEELS_MESH004: THREE.Mesh;
    FRONT_WHEELS_MESH004_1: THREE.Mesh;
    FRONT_WHEELS_MESH004_2: THREE.Mesh;
    MIRRORS_MESH003: THREE.Mesh;
    MIRRORS_MESH003_1: THREE.Mesh;
    MIRRORS_MESH003_2: THREE.Mesh;
    MIRRORS_MESH003_3: THREE.Mesh;
    MIRRORS_MESH003_4: THREE.Mesh;
    MIRRORS_MESH003_5: THREE.Mesh;
    MIRRORS_MESH003_6: THREE.Mesh;
  };
  materials: {
    Concrete_1: THREE.MeshBasicMaterial;
    Concrete_2: THREE.MeshBasicMaterial;
    Concrete_4: THREE.MeshBasicMaterial;
    Grass: THREE.MeshBasicMaterial;
    Concrete_5: THREE.MeshBasicMaterial;
    Bank_Brown: THREE.MeshBasicMaterial;
    Bank_Window: THREE.MeshBasicMaterial;
    Bank_Dark_Iron: THREE.MeshBasicMaterial;
    Bank_White: THREE.MeshBasicMaterial;
    Bank_Orange: THREE.MeshBasicMaterial;
    Bank_Yellow: THREE.MeshBasicMaterial;
    Bank_Block_Bush_Base: THREE.MeshBasicMaterial;
    Bank_Block_Bush_Bark: THREE.MeshBasicMaterial;
    Van_Base: THREE.MeshBasicMaterial;
    Van_window: THREE.MeshBasicMaterial;
    Van_Shade: THREE.MeshBasicMaterial;
    Van_Plastic: THREE.MeshBasicMaterial;
    VanWindow_Shade: THREE.MeshBasicMaterial;
    Van_Shade_2: THREE.MeshBasicMaterial;
    ["Frontlight_1.001"]: THREE.MeshBasicMaterial;
    ["Backlight.001"]: THREE.MeshBasicMaterial;
    Car_Wheel_Chrome_Shade_2: THREE.MeshBasicMaterial;
    Car_Wheel_Chrome_Shade: THREE.MeshBasicMaterial;
    Van_Wheel_Chrome_Shade_2: THREE.MeshBasicMaterial;
    ["Car_window.001"]: THREE.MeshBasicMaterial;
  };
};

export const Bank3DModel = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(bank3DModelFile) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-6.11, 4.65, -18.65]} scale={3.34}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials.Concrete_1}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials.Bank_Dark_Iron}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials.Bank_Window}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={materials.Bank_White}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={materials.Bank_Orange}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={materials.Bank_Yellow}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={materials.Bank_Brown}
        />
      </group>
      <mesh
        geometry={nodes.A_C.geometry}
        material={materials.Bank_White}
        position={[7.03, 9.62, -19.64]}
        scale={0.65}
      />
      <group position={[-11.02, 1.59, -8.4]} scale={0.59}>
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials.Bank_Block_Bush_Base}
        />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials.Bank_Block_Bush_Bark}
        />
      </group>
      <mesh
        geometry={nodes.SIDE_WALK.geometry}
        material={materials.Concrete_5}
        position={[0, 0, -18.01]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-10.62, -0.07, -1]}
      />
      <mesh
        geometry={nodes.AUTO_SERVICE.geometry}
        material={materials.Concrete_1}
        position={[17.79, 0.84, -21.04]}
        scale={[1, 1, 4.42]}
      />
      <group position={[-6.8, 0, -13.09]}>
        <mesh
          geometry={nodes.VAN_BODY_MESH.geometry}
          material={materials.Van_Base}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_1.geometry}
          material={materials.Van_window}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_2.geometry}
          material={materials.Van_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_3.geometry}
          material={materials.Van_Plastic}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_4.geometry}
          material={materials.VanWindow_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_5.geometry}
          material={materials.Van_Shade_2}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_6.geometry}
          material={materials["Frontlight_1.001"]}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH_7.geometry}
          material={materials["Backlight.001"]}
        />
        <group position={[0, 0, -2.6]} scale={0.34}>
          <mesh
            geometry={nodes.BACK_WHEELS_MESH001.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH001_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH001_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group scale={0.34}>
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH001.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH001_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH001_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group
          position={[0, 0.11, 0.3]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.06, 0.06, 0.08]}
        >
          <mesh
            geometry={nodes.MIRRORS_MESH.geometry}
            material={materials["Car_window.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_1.geometry}
            material={materials.Van_Shade_2}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_2.geometry}
            material={materials["Frontlight_1.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_3.geometry}
            material={materials.Van_Plastic}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_4.geometry}
            material={materials.Van_Base}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_5.geometry}
            material={materials.Van_Shade}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH_6.geometry}
            material={materials.Van_Base}
          />
        </group>
      </group>
      <group position={[3.92, 0, -14.01]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.VAN_BODY_MESH001.geometry}
          material={materials.Van_Base}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_1.geometry}
          material={materials.Van_window}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_2.geometry}
          material={materials.Van_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_3.geometry}
          material={materials.Van_Plastic}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_4.geometry}
          material={materials.VanWindow_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_5.geometry}
          material={materials.Van_Shade_2}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_6.geometry}
          material={materials["Frontlight_1.001"]}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH001_7.geometry}
          material={materials["Backlight.001"]}
        />
        <group position={[0, 0, -2.6]} scale={0.34}>
          <mesh
            geometry={nodes.BACK_WHEELS_MESH002.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH002_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH002_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group scale={0.34}>
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH002.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH002_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH002_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group
          position={[0, 0.11, 0.3]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.06, 0.06, 0.08]}
        >
          <mesh
            geometry={nodes.MIRRORS_MESH001.geometry}
            material={materials["Car_window.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_1.geometry}
            material={materials.Van_Shade_2}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_2.geometry}
            material={materials["Frontlight_1.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_3.geometry}
            material={materials.Van_Plastic}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_4.geometry}
            material={materials.Van_Base}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_5.geometry}
            material={materials.Van_Shade}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH001_6.geometry}
            material={materials.Van_Base}
          />
        </group>
      </group>
      <group position={[-1.42, 0, -13.09]} rotation={[0, 0.27, 0]}>
        <mesh
          geometry={nodes.VAN_BODY_MESH002.geometry}
          material={materials.Van_Base}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_1.geometry}
          material={materials.Van_window}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_2.geometry}
          material={materials.Van_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_3.geometry}
          material={materials.Van_Plastic}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_4.geometry}
          material={materials.VanWindow_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_5.geometry}
          material={materials.Van_Shade_2}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_6.geometry}
          material={materials["Frontlight_1.001"]}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH002_7.geometry}
          material={materials["Backlight.001"]}
        />
        <group position={[0, 0, -2.6]} scale={0.34}>
          <mesh
            geometry={nodes.BACK_WHEELS_MESH003.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH003_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH003_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group scale={0.34}>
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH003.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH003_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH003_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group
          position={[0, 0.11, 0.3]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.06, 0.06, 0.08]}
        >
          <mesh
            geometry={nodes.MIRRORS_MESH002.geometry}
            material={materials["Car_window.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_1.geometry}
            material={materials.Van_Shade_2}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_2.geometry}
            material={materials["Frontlight_1.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_3.geometry}
            material={materials.Van_Plastic}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_4.geometry}
            material={materials.Van_Base}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_5.geometry}
            material={materials.Van_Shade}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH002_6.geometry}
            material={materials.Van_Base}
          />
        </group>
      </group>
      <group position={[14.55, 0, -9.03]} rotation={[-Math.PI, 0.12, -Math.PI]}>
        <mesh
          geometry={nodes.VAN_BODY_MESH003.geometry}
          material={materials.Van_Base}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_1.geometry}
          material={materials.Van_window}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_2.geometry}
          material={materials.Van_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_3.geometry}
          material={materials.Van_Plastic}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_4.geometry}
          material={materials.VanWindow_Shade}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_5.geometry}
          material={materials.Van_Shade_2}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_6.geometry}
          material={materials["Frontlight_1.001"]}
        />
        <mesh
          geometry={nodes.VAN_BODY_MESH003_7.geometry}
          material={materials["Backlight.001"]}
        />
        <group position={[0, 0, -2.6]} scale={0.34}>
          <mesh
            geometry={nodes.BACK_WHEELS_MESH004.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH004_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.BACK_WHEELS_MESH004_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group scale={0.34}>
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH004.geometry}
            material={materials.Car_Wheel_Chrome_Shade_2}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH004_1.geometry}
            material={materials.Car_Wheel_Chrome_Shade}
          />
          <mesh
            geometry={nodes.FRONT_WHEELS_MESH004_2.geometry}
            material={materials.Van_Wheel_Chrome_Shade_2}
          />
        </group>
        <group
          position={[0, 0.11, 0.3]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.06, 0.06, 0.08]}
        >
          <mesh
            geometry={nodes.MIRRORS_MESH003.geometry}
            material={materials["Car_window.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_1.geometry}
            material={materials.Van_Shade_2}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_2.geometry}
            material={materials["Frontlight_1.001"]}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_3.geometry}
            material={materials.Van_Plastic}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_4.geometry}
            material={materials.Van_Base}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_5.geometry}
            material={materials.Van_Shade}
          />
          <mesh
            geometry={nodes.MIRRORS_MESH003_6.geometry}
            material={materials.Van_Base}
          />
        </group>
      </group>
      <mesh geometry={nodes.ROAD_1.geometry} material={materials.Concrete_1} />
      <mesh geometry={nodes.ROAD_2.geometry} material={materials.Concrete_2} />
      <mesh geometry={nodes.ROAD_3.geometry} material={materials.Concrete_4} />
      <mesh geometry={nodes.ROAD_4.geometry} material={materials.Grass} />
      <mesh geometry={nodes.ROAD_5.geometry} material={materials.Concrete_5} />
      <mesh geometry={nodes.ROAD_6.geometry} material={materials.Bank_Brown} />
      <mesh geometry={nodes.ROAD_7.geometry} material={materials.Bank_Window} />
    </group>
  );
};

useGLTF.preload(bank3DModelFile);
