/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 assets/models/Car.glb -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CAR_BODY_MESH: THREE.Mesh
    CAR_BODY_MESH_1: THREE.Mesh
    CAR_BODY_MESH_2: THREE.Mesh
    CAR_BODY_MESH_3: THREE.Mesh
    CAR_BODY_MESH_4: THREE.Mesh
    CAR_BODY_MESH_5: THREE.Mesh
    CAR_BODY_MESH_6: THREE.Mesh
    CAR_BODY_MESH_7: THREE.Mesh
    CAR_BODY_MESH_8: THREE.Mesh
    CAR_BODY_MESH_9: THREE.Mesh
    MIRRORS_MESH: THREE.Mesh
    MIRRORS_MESH_1: THREE.Mesh
    MIRRORS_MESH_2: THREE.Mesh
    MIRRORS_MESH_3: THREE.Mesh
    MIRRORS_MESH_4: THREE.Mesh
    MIRRORS_MESH_5: THREE.Mesh
    MIRRORS_MESH_6: THREE.Mesh
    FRONT_WHEELS_MESH: THREE.Mesh
    FRONT_WHEELS_MESH_1: THREE.Mesh
    FRONT_WHEELS_MESH_2: THREE.Mesh
    FRONT_WHEELS_MESH_3: THREE.Mesh
    FRONT_WHEELS_MESH_4: THREE.Mesh
    BACK_WHEELS_MESH: THREE.Mesh
    BACK_WHEELS_MESH_1: THREE.Mesh
    BACK_WHEELS_MESH_2: THREE.Mesh
    BACK_WHEELS_MESH_3: THREE.Mesh
    BACK_WHEELS_MESH_4: THREE.Mesh
  }
  materials: {
    Car_High: THREE.MeshBasicMaterial
    Car_Base: THREE.MeshBasicMaterial
    Car_Plastic: THREE.MeshBasicMaterial
    Car_Shade: THREE.MeshBasicMaterial
    Car_Shade_2: THREE.MeshBasicMaterial
    Frontlight_1: THREE.MeshBasicMaterial
    Car_window: THREE.MeshBasicMaterial
    Car_Interior: THREE.MeshBasicMaterial
    Car_Window_Shade: THREE.MeshBasicMaterial
    Backlight: THREE.MeshBasicMaterial
    Car_Wheel_Chrome_Base: THREE.MeshBasicMaterial
    Car_Wheel_Chrome_Shade: THREE.MeshBasicMaterial
    Car_Wheel_Chrome_Shade_2: THREE.MeshBasicMaterial
    Car_Wheel_Red: THREE.MeshBasicMaterial
    Car_Wheel_Rubber: THREE.MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../assets/models/Car.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.55, 2.05]} scale={[0.24, 0.32, 0.24]}>
        <mesh geometry={nodes.CAR_BODY_MESH.geometry} material={materials.Car_High} />
        <mesh geometry={nodes.CAR_BODY_MESH_1.geometry} material={materials.Car_Base} />
        <mesh geometry={nodes.CAR_BODY_MESH_2.geometry} material={materials.Car_Plastic} />
        <mesh geometry={nodes.CAR_BODY_MESH_3.geometry} material={materials.Car_Shade} />
        <mesh geometry={nodes.CAR_BODY_MESH_4.geometry} material={materials.Car_Shade_2} />
        <mesh geometry={nodes.CAR_BODY_MESH_5.geometry} material={materials.Frontlight_1} />
        <mesh geometry={nodes.CAR_BODY_MESH_6.geometry} material={materials.Car_window} />
        <mesh geometry={nodes.CAR_BODY_MESH_7.geometry} material={materials.Car_Interior} />
        <mesh geometry={nodes.CAR_BODY_MESH_8.geometry} material={materials.Car_Window_Shade} />
        <mesh geometry={nodes.CAR_BODY_MESH_9.geometry} material={materials.Backlight} />
        <group position={[0, -1.74, -8.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.26, 0.26, 0.24]}>
          <mesh geometry={nodes.MIRRORS_MESH.geometry} material={materials.Car_window} />
          <mesh geometry={nodes.MIRRORS_MESH_1.geometry} material={materials.Car_Base} />
          <mesh geometry={nodes.MIRRORS_MESH_2.geometry} material={materials.Frontlight_1} />
          <mesh geometry={nodes.MIRRORS_MESH_3.geometry} material={materials.Car_Plastic} />
          <mesh geometry={nodes.MIRRORS_MESH_4.geometry} material={materials.Car_High} />
          <mesh geometry={nodes.MIRRORS_MESH_5.geometry} material={materials.Car_Shade} />
          <mesh geometry={nodes.MIRRORS_MESH_6.geometry} material={materials.Car_Base} />
        </group>
      </group>
      <group position={[0, 0.36, 1.4]} scale={[0.13, 0.35, 0.35]}>
        <mesh geometry={nodes.FRONT_WHEELS_MESH.geometry} material={materials.Car_Wheel_Chrome_Base} />
        <mesh geometry={nodes.FRONT_WHEELS_MESH_1.geometry} material={materials.Car_Wheel_Chrome_Shade} />
        <mesh geometry={nodes.FRONT_WHEELS_MESH_2.geometry} material={materials.Car_Wheel_Chrome_Shade_2} />
        <mesh geometry={nodes.FRONT_WHEELS_MESH_3.geometry} material={materials.Car_Wheel_Red} />
        <mesh geometry={nodes.FRONT_WHEELS_MESH_4.geometry} material={materials.Car_Wheel_Rubber} />
      </group>
      <group position={[0, 0.36, -1.53]} scale={[0.13, 0.35, 0.35]}>
        <mesh geometry={nodes.BACK_WHEELS_MESH.geometry} material={materials.Car_Wheel_Chrome_Base} />
        <mesh geometry={nodes.BACK_WHEELS_MESH_1.geometry} material={materials.Car_Wheel_Chrome_Shade} />
        <mesh geometry={nodes.BACK_WHEELS_MESH_2.geometry} material={materials.Car_Wheel_Chrome_Shade_2} />
        <mesh geometry={nodes.BACK_WHEELS_MESH_3.geometry} material={materials.Car_Wheel_Red} />
        <mesh geometry={nodes.BACK_WHEELS_MESH_4.geometry} material={materials.Car_Wheel_Rubber} />
      </group>
    </group>
  )
}

useGLTF.preload('/../assets/models/Car.glb')
