/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 src/assets/models/coins/Coins.glb -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import coins3DModelFile from "../../assets/models/coins/Coins.glb";
import { useTurnTable } from "../../hooks/use-turn-table";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002_1: THREE.Mesh;
    Cylinder002_2: THREE.Mesh;
    Cylinder002_3: THREE.Mesh;
  };
  materials: {
    Metal: THREE.MeshBasicMaterial;
    Gold: THREE.MeshBasicMaterial;
    Metal_shade: THREE.MeshBasicMaterial;
  };
};

export function Coins3dModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(coins3DModelFile) as GLTFResult;
  const { group } = useTurnTable();

  return (
    <group {...props} dispose={null} ref={group} scale={0.55}>
      <mesh
        geometry={nodes.Cylinder002_1.geometry}
        material={materials.Metal}
      />
      <mesh geometry={nodes.Cylinder002_2.geometry} material={materials.Gold} />
      <mesh
        geometry={nodes.Cylinder002_3.geometry}
        material={materials.Metal_shade}
      />
    </group>
  );
}

useGLTF.preload(coins3DModelFile);
